version: 2.1
orbs:
    python: circleci/python@2.0.1
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run:
          command: |
            pip install pytest
            pytest --junitxml=test-results/junit.xml
            cd Part-2/
            MTTDtest.py
      - store_test_results:
          path: test-results

workflows:
  test_get_repo:
    jobs:
      - build-and-test
